/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package se.iths;

import org.junit.jupiter.api.*;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.SQLIntegrityConstraintViolationException;

import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.fail;

class CheckConstraintTest {

    private static final String CREATE_QUERY =
    """
    CREATE TABLE Student (
     StudentId int NOT NULL,
     Name varchar(255) NOT NULL,
     Age int,
     CHECK (Age>=18)
    );
    """;

    private Configuration config = new Configuration();
    private Connection con = null;
    @BeforeEach
    public void setUp() throws Exception {

        con = DriverManager.getConnection(config.getDbUrl(), config.getDbUser(), config.getDbPassword());
        con.createStatement().execute("DROP TABLE IF EXISTS Student");
        con.createStatement().execute(CREATE_QUERY);
    }

    @AfterEach
    public void tearDown() throws Exception {
        con.close();
    }

    @Test
    void shouldAddDataWithAge18() throws Exception{
        con.createStatement().execute("INSERT INTO Student (StudentId, Name, Age) VALUES (1, \"Nisse\", 18)");
    }

    @Test
    void shouldANotAcceptDataWithAge17() throws Exception{
        try {
            con.createStatement().execute("INSERT INTO Student (StudentId, Name, Age) VALUES (2, \"Olle\", 17)");
        }catch (SQLException e){
            assertTrue(true, "Test worked");
            return;
        }
        fail("Database constraint has failed");
    }

}
