/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package se.iths;

import org.junit.jupiter.api.*;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLIntegrityConstraintViolationException;

import static org.junit.jupiter.api.Assertions.fail;

/**
 * GRANT SUPER ON *.* TO iths@'%';
 * Vi måste ha SUPER rättigheter för att få skapa triggers
 */
class TriggerConstraintTest {

    private static final String CREATE_QUERY =
"""
CREATE TABLE Student (
    ID int NOT NULL,
    Name varchar(255) NOT NULL,
    Age int NOT NULL 0
);
""";
    private static final String CREATE_TRIGGER =
"""
delimiter //
CREATE TRIGGER student_age_trigger BEFORE INSERT
ON Student
FOR EACH ROW
IF NEW.Age < 18 THEN
SIGNAL SQLSTATE '50001' SET MESSAGE_TEXT = 'Student must be older than 18.';
END IF; //
delimiter ;
""";

    private Configuration config = new Configuration();
    private Connection con = null;
    @BeforeEach
    public void setUp() throws Exception {

        con = DriverManager.getConnection(config.getDbUrl(), config.getDbUser(), config.getDbPassword());
        con.createStatement().execute("DROP TABLE IF EXISTS Student");
        con.createStatement().execute(CREATE_QUERY);
        try {
            con.createStatement().execute("INSERT INTO Student (StudentId, Name, Age) VALUES (1, \"Nisse\", 17)");
        }catch (Exception e){
            System.out.println(e);
        }
        System.out.println("Hello World");
    }

    @AfterEach
    public void tearDown() throws Exception {
        con.close();
    }

    @Disabled @Test void shouldFailWithCorrectException() throws Exception {
        fail("not yet implemented!");
    }
}
