/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package se.iths;

import org.junit.jupiter.api.*;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLIntegrityConstraintViolationException;

import static org.junit.jupiter.api.Assertions.fail;

class TriggerConstraintTest {

    private static final String CREATE_QUERY =
"""
CREATE TABLE Student (
    ID int NOT NULL,
    Name varchar(255) NOT NULL,
    Age int NOT NULL 0
);
""";
    private static final String CREATE_TRIGGER =
"""
    CREATE TRIGGER agecheck 
    BEFORE INSERT 
    ON Student FOR EACH ROW IF NEW.Age < 17
    THEN SET NEW.Age = 0; END IF;
""";

    private Configuration config = new Configuration();
    private Connection con = null;
    @BeforeEach
    public void setUp() throws Exception {

        con = DriverManager.getConnection(config.getDbUrl(), config.getDbUser(), config.getDbPassword());
        con.createStatement().execute("DROP TABLE IF EXISTS Student");
        try {
            con.createStatement().execute(CREATE_QUERY);
        }catch (Exception e){
            System.out.println(e);
        }
    }

    @AfterEach
    public void tearDown() throws Exception {
        con.close();
    }

    @Disabled @Test void shouldFailWithCorrectException() throws Exception {
        fail("not yet implemented!");
    }
}
